import { writeFile } from 'node:fs/promises';
import { motion, palette, radius, resourceColors, spacing, typography } from './index.ts';

const flatten = (value, prefix = []) => Object.entries(value).flatMap(([key, child]) => {
  const path = [...prefix, key];

  return typeof child === 'object' && child !== null
    ? flatten(child, path)
    : [[path, child]];
});

const cssName = (path) => {
  const normalized = [...path];

  if (normalized[0] === 'spacing') normalized[0] = 'space';
  if (normalized[0] === 'typography') {
    normalized[0] = 'type';
    if (normalized.at(-1) === 'lineHeight') normalized[normalized.length - 1] = 'line';
  }

  return '--token-' + normalized.join('-').replaceAll('_', '-');
};
const unit = (path, value) => {
  if (path[0] === 'spacing' || path[0] === 'radius') return String(value) + 'px';
  if (path[0] === 'typography' && (path.at(-1) === 'size' || path.at(-1) === 'lineHeight')) {
    return String(value) + 'px';
  }
  if (path[0] === 'motion') return String(value) + 'ms';

  return String(value);
};

const themeBlock = (themeName, theme) => [
  themeName === 'light' ? ':root {' : "[data-theme='" + themeName + "'] {",
  themeName === 'light' ? '    color-scheme: light;' : '    color-scheme: dark;',
  ...flatten(theme).map(([path, value]) => '    ' + cssName(path) + ': ' + value + ';'),
  ...flatten(resourceColors, ['resource']).map(([path, value]) => '    ' + cssName(path) + ': ' + value + ';'),
  ...flatten(spacing, ['spacing']).map(([path, value]) => '    ' + cssName(path) + ': ' + unit(path, value) + ';'),
  ...flatten(radius, ['radius']).map(([path, value]) => '    ' + cssName(path) + ': ' + unit(path, value) + ';'),
  ...flatten(typography, ['typography']).map(([path, value]) => '    ' + cssName(path) + ': ' + unit(path, value) + ';'),
  ...flatten(motion, ['motion']).map(([path, value]) => '    ' + cssName(path) + ': ' + unit(path, value) + ';'),
  '}',
].join('\n');

const css = [
  '/* Generated from index.ts. Do not edit this file directly. */',
  themeBlock('light', palette.light),
  '',
  themeBlock('dark', palette.dark),
  '',
  '@media (prefers-reduced-motion: reduce) {',
  '    :root, [data-theme="dark"] {',
  '        --token-motion-fast: var(--token-motion-instant);',
  '        --token-motion-base: var(--token-motion-instant);',
  '        --token-motion-slow: var(--token-motion-instant);',
  '        --token-motion-deliberate: var(--token-motion-instant);',
  '    }',
  '}',
  '',
].join('\n');

await writeFile(new URL('./institutional.css', import.meta.url), css);
